name: Koala
channels:
  - conda-forge
dependencies:
  - conda
  - python=3.8
  - ipykernel #this makes the env show up in the list of jupyter environments
  - numpy
  - scipy
  - matplotlib
  - pip
  - pytest
  - flake8
  - kwant
  - pip:
    # works for regular pip packages
    - python-sat #the frontend to the sat solver
    - sphinxcontrib-apidoc # required for doc gen