name: Project Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -e .
      
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Test with pytest
        run: |
          pytest -c pytest.ini --cov=koala --cov-report=xml
          # pytest -c pytest_notebooks.ini
      
      - uses: codecov/codecov-action@v2
  # hpc:
  #   runs-on: hpc
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: HPC Step
  #       uses: imperialcollegelondon/hpc_github_action@main
  #       with:
  #         job-script-contents: |
  #           conda install -y python pip
  #           pip install --upgrade --upgrade-strategy eager -e .
  #           pytest -c pytest_notebooks.ini
            